;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		ace-window
		hydra-multiple-cursors/body
		undo-tree-visualize
		viper-append
		viper-backward-char
		viper-backward-word
		viper-beginning-of-line
		viper-del-backward-char-in-insert
		viper-delete-char
		viper-end-of-word
		viper-ex
		viper-forward-char
		viper-goto-eol
		viper-insert
		viper-intercept-ESC-key
		viper-next-line
		viper-open-line
		viper-previous-line
		))

(setq mc/cmds-to-run-once
      '(
		hydra-multiple-cursors/mc/insert-letters-and-exit
		hydra-multiple-cursors/mc/insert-numbers-and-exit
		hydra-multiple-cursors/mc/mark-next-like-this
		hydra-multiple-cursors/mc/mark-previous-like-this
		hydra-multiple-cursors/mc/unmark-next-like-this
		hydra-multiple-cursors/mc/unmark-previous-like-this
		org-self-insert-command
		))
