(setq viper-inhibit-startup-message 't)
(setq viper-expert-level '5)
(setq viper-case-fold-search 't)
;; (define-key viper-vi-basic-map (kbd "t") 'rjsx-jump-tag)
(define-key viper-vi-basic-map (kbd "u") 'undo-tree-visualize)
(define-key viper-vi-basic-map (kbd "c") 'comment-line)
(define-key viper-vi-basic-map (kbd "+") 'text-scale-increase)
(define-key viper-vi-basic-map (kbd "-") 'text-scale-decrease)
(define-key viper-vi-basic-map (kbd ".") 'viper-paren-match)
(define-key viper-vi-basic-map (kbd "g") 'ace-window)
(define-key viper-vi-basic-map (kbd "m") 'set-mark-command)
(define-key viper-vi-basic-map (kbd "s") 'kill-region)
(define-key viper-vi-basic-map (kbd "ñ") 'end-of-line)
(define-key viper-vi-basic-map (kbd "q") 'beginning-of-line)
(define-key viper-vi-basic-map (kbd "z y") 'hydra-yasnippet/body)
(define-key viper-vi-basic-map (kbd "z c") 'hydra-multiple-cursors/body)
(define-key viper-vi-basic-map (kbd "z j") 'hydra-dumb-jump/body)
(define-key viper-vi-basic-map (kbd "z r") 'hydra-restclient/body)
(define-key viper-vi-basic-map (kbd "z s") 'hydra-scroll-window/body)
(define-key viper-vi-basic-map (kbd "z m") 'hydra-move-avy/body)
(define-key viper-vi-basic-map (kbd "z f") 'hydra-find-word)
(define-key viper-vi-basic-map (kbd "z b") 'switch-to-buffer)
(define-key viper-vi-basic-map (kbd "z k") 'kill-buffer)
